- hosts: all

  vars_prompt:
    - name: "username"
      prompt: "Enter username"
      default: app
      private: no
    - name: "password"
      prompt: "Enter password"
      default: "S(X84gZQZxBbi~E6rt_m"
      private: yes
      encrypt: "sha512_crypt"

  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Create User
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups: wheel

    - name: Set wheel group nopasswd
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel\s'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        state: present

    - name: Open http port
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', 'id_rsa.pub') }}"

    - name: Edit sshd_config PermitRootLogin no
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        insertafter: "^#PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Edit sshd_config PasswordAuthentication no
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        insertafter: "^#PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted
